version: '3.1'

services:

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: feedbackcenter
    ports:
      - 3306:3306

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feedbackcenter
    ports:
      - 5432:5432
