create table authorities (id bigint not null, authority varchar(255), employee_id bigint not null, primary key (id)) engine=InnoDB;
create table base_question (id bigint not null, category varchar(60), description varchar(120), position varchar(60), primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, email varchar(255) not null, enabled bit not null, name varchar(120), password varchar(60), position varchar(60), roles varchar(255), primary key (id)) engine=InnoDB;
create table feedback (relationship varchar(255), state varchar(255), evaluated_id bigint not null, evaluator_id bigint not null, primary key (evaluated_id, evaluator_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table question (id bigint not null, category varchar(60), description varchar(120), evaluation varchar(255), example varchar(2000), improvement varchar(2000), title varchar(60), evaluated_id bigint not null, evaluator_id bigint not null, primary key (id)) engine=InnoDB;
alter table authorities add constraint UK_authorities_employee_authority unique (employee_id, authority);
alter table employee add constraint UK_employee_email unique (email);
alter table authorities add constraint FK_authorities_employeeid foreign key (employee_id) references employee (id);
alter table feedback add constraint FK_feedback_evaluatedid foreign key (evaluated_id) references employee (id);
alter table feedback add constraint FK_feedback_evaluatorid foreign key (evaluator_id) references employee (id);
alter table question add constraint FK_question_evaluatedid foreign key (evaluated_id) references employee (id);
alter table question add constraint FK_question_evaluator_id foreign key (evaluator_id) references employee (id);